site_name: Rail-RNA v0.2
pages:
- Home: index.md
- Installation: installation.md
- Tutorial: tutorial.md
- Deliverables: deliverables.md
- dbGaP on EMR: dbgap.md
- Reference: reference.md
theme: readthedocs
